import type {
  Cafe,
  MenuItem,
  Order,
  PreOrderSlot,
  Reward,
  Student,
  TopUpOption,
  Transaction,
} from "./types";
import { images } from "./images";

export const CAMPUS_NAME = "UiTM Lendu";
export const CAMPUS_FULL_NAME =
  "UiTM Cawangan Melaka Kampus Alor Gajah (Lendu)";
export const CAMPUS_ADDRESS = "KM 26, Jalan Lendu, 78000 Alor Gajah, Melaka";
export const CAMPUS_SUPPORT_PHONE = "+6065582000";
export const CAMPUS_SUPPORT_PHONE_DISPLAY = "(+606) 558 2000";
export const CAMPUS_SUPPORT_EMAIL = "pnc.inqka@uitm.edu.my";

export const APP_NAME = "LenduEats";
export const APP_TAGLINE = `Campus Food & Convenience · ${CAMPUS_NAME}`;
export const CAFE_OPEN_HOURS = "8:00 AM – 11:00 PM";

export const DEMO_CREDENTIALS = {
  studentId: "2025893182",
  password: "kampus123",
};

export const student: Student = {
  id: "stu-001",
  name: "Mohammad Hadif",
  studentId: "2025893182",
  email: "hadif@student.uitm.edu.my",
  faculty: "Faculty of Hotel & Tourism Management (FHTM)",
  avatar: "MH",
  walletBalance: 48.5,
  points: 1240,
  tier: "Silver",
};

export const cafes: Cafe[] = [
  {
    id: "cafe-1",
    name: "Cafe Bentara",
    location: "Dewan Bentara, KPP1",
    rating: 4.6,
    reviewCount: 412,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-1"],
    category: "Food Hall",
    prepTime: "10–15 min",
    isOpen: true,
    tags: ["Halal", "Main Cafeteria"],
  },
  {
    id: "cafe-2",
    name: "Dewan Laksamana",
    location: "Dewan Laksamana, KPP1",
    rating: 4.3,
    reviewCount: 186,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-2"],
    category: "Food Hall",
    prepTime: "12–18 min",
    isOpen: true,
    tags: ["Halal", "Full Day"],
  },
  {
    id: "cafe-3",
    name: "Cafe Jebat",
    location: "Kolej Jebat",
    rating: 4.4,
    reviewCount: 268,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-3"],
    category: "Food Hall",
    prepTime: "8–12 min",
    isOpen: true,
    tags: ["Halal", "Kolej Favourite"],
  },
  {
    id: "cafe-4",
    name: "Cafe Tun Sabariah",
    location: "Kolej Tun Sabariah",
    rating: 4.5,
    reviewCount: 224,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-4"],
    category: "Food Hall",
    prepTime: "8–12 min",
    isOpen: true,
    tags: ["Halal", "Budget Friendly"],
  },
  {
    id: "cafe-5",
    name: "Cafe Sunshine",
    location: "KPP1, Student Area",
    rating: 4.7,
    reviewCount: 301,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-5"],
    category: "Food Hall",
    prepTime: "5–8 min",
    isOpen: true,
    tags: ["Coffee", "Light Bites"],
  },
  {
    id: "cafe-6",
    name: "Pakya Sinar",
    location: "KPP2, Food Court",
    rating: 4.4,
    reviewCount: 356,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-6"],
    category: "Food Hall",
    prepTime: "8–12 min",
    isOpen: true,
    tags: ["Halal", "Student Favourite"],
  },
  {
    id: "cafe-7",
    name: "Cafe Richiamo",
    location: "Perpustakaan KPP1",
    rating: 4.8,
    reviewCount: 192,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-7"],
    category: "Coffee & Italian",
    prepTime: "5–8 min",
    isOpen: true,
    tags: ["Coffee", "Study Spot"],
  },
  {
    id: "cafe-8",
    name: "Cafe Pedas Manis",
    location: "KPP3, Faculty Block",
    rating: 4.5,
    reviewCount: 178,
    openHours: CAFE_OPEN_HOURS,
    image: images.cafes["cafe-8"],
    category: "Warung Nusantara",
    prepTime: "10–15 min",
    isOpen: true,
    tags: ["Halal", "Pedas & Manis"],
  },
];

export const menuItems: MenuItem[] = [
  // Cafe Bentara
  {
    id: "m-4",
    cafeId: "cafe-1",
    name: "Teh Tarik",
    description: "Classic pulled milk tea",
    price: 2.5,
    image: images.menu["m-4"],
    category: "Drinks",
    popular: true,
  },
  {
    id: "m-6",
    cafeId: "cafe-1",
    name: "Nasi Lemak Biasa",
    description: "Coconut rice, sambal, egg, peanuts & anchovies",
    price: 5.0,
    image: images.menu["m-6"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-7",
    cafeId: "cafe-1",
    name: "Nasi Lemak Ayam Goreng",
    description: "Nasi lemak with crispy fried chicken",
    price: 8.0,
    image: images.menu["m-7"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-19",
    cafeId: "cafe-1",
    name: "Nasi Goreng Kampung",
    description: "Village-style fried rice with ikan bilis & kangkung",
    price: 7.0,
    image: images.menu["m-19"],
    category: "Rice",
  },
  {
    id: "m-20",
    cafeId: "cafe-1",
    name: "Ayam Goreng Berempah",
    description: "Crispy spiced fried chicken with rice & sambal",
    price: 9.0,
    image: images.menu["m-20"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-21",
    cafeId: "cafe-1",
    name: "Teh O Ais",
    description: "Iced tea without milk",
    price: 2.0,
    image: images.menu["m-21"],
    category: "Drinks",
  },
  // Dewan Laksamana
  {
    id: "m-1",
    cafeId: "cafe-2",
    name: "Nasi Ayam Berempah",
    description: "Fragrant rice with spiced grilled chicken & sambal",
    price: 8.5,
    image: images.menu["m-1"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-2",
    cafeId: "cafe-2",
    name: "Burger Daging Special",
    description: "Beef patty, cheese, caramelised onion & fries",
    price: 12.0,
    image: images.menu["m-2"],
    category: "Western",
    popular: true,
  },
  {
    id: "m-22",
    cafeId: "cafe-2",
    name: "Nasi Campur",
    description: "White rice with assorted lauk of the day",
    price: 9.0,
    image: images.menu["m-22"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-23",
    cafeId: "cafe-2",
    name: "Sup Tulang",
    description: "Beef bone soup with bread or rice",
    price: 10.0,
    image: images.menu["m-23"],
    category: "Soup",
  },
  {
    id: "m-24",
    cafeId: "cafe-2",
    name: "Sirap Bandung",
    description: "Rose syrup milk drink, iced",
    price: 3.5,
    image: images.menu["m-24"],
    category: "Drinks",
  },
  // Cafe Jebat
  {
    id: "m-8",
    cafeId: "cafe-3",
    name: "Roti Canai Kosong",
    description: "Flaky flatbread with dhal curry",
    price: 2.0,
    image: images.menu["m-8"],
    category: "Bread",
  },
  {
    id: "m-9",
    cafeId: "cafe-3",
    name: "Milo Ais",
    description: "Iced chocolate malt drink",
    price: 3.0,
    image: images.menu["m-9"],
    category: "Drinks",
  },
  {
    id: "m-25",
    cafeId: "cafe-3",
    name: "Roti Telur",
    description: "Egg-stuffed roti canai with dhal & sambal",
    price: 4.0,
    image: images.menu["m-25"],
    category: "Bread",
    popular: true,
  },
  {
    id: "m-26",
    cafeId: "cafe-3",
    name: "Mee Sup",
    description: "Clear broth noodles with chicken & vegetables",
    price: 6.0,
    image: images.menu["m-26"],
    category: "Noodles",
  },
  {
    id: "m-27",
    cafeId: "cafe-3",
    name: "Nescafe Ais",
    description: "Iced instant coffee with milk",
    price: 3.5,
    image: images.menu["m-27"],
    category: "Drinks",
  },
  // Cafe Tun Sabariah
  {
    id: "m-3",
    cafeId: "cafe-4",
    name: "Mee Goreng Mamak",
    description: "Wok-fried noodles with egg, tofu & vegetables",
    price: 7.0,
    image: images.menu["m-3"],
    category: "Noodles",
  },
  {
    id: "m-5",
    cafeId: "cafe-4",
    name: "Air Kosong",
    description: "Mineral water 500ml",
    price: 1.5,
    image: images.menu["m-5"],
    category: "Drinks",
  },
  {
    id: "m-28",
    cafeId: "cafe-4",
    name: "Nasi Goreng Pattaya",
    description: "Fried rice wrapped in omelette with chicken",
    price: 8.0,
    image: images.menu["m-28"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-29",
    cafeId: "cafe-4",
    name: "Ayam Penyet",
    description: "Smashed fried chicken with sambal & ulam",
    price: 9.0,
    image: images.menu["m-29"],
    category: "Rice",
  },
  {
    id: "m-30",
    cafeId: "cafe-4",
    name: "Limau Ais",
    description: "Fresh lime juice with ice",
    price: 3.0,
    image: images.menu["m-30"],
    category: "Drinks",
  },
  // Cafe Sunshine
  {
    id: "m-12",
    cafeId: "cafe-5",
    name: "Croissant Butter",
    description: "Freshly baked buttery croissant",
    price: 5.5,
    image: images.menu["m-12"],
    category: "Pastries",
    vegetarian: true,
  },
  {
    id: "m-13",
    cafeId: "cafe-5",
    name: "Blueberry Muffin",
    description: "Soft muffin with blueberry filling",
    price: 6.0,
    image: images.menu["m-13"],
    category: "Pastries",
    vegetarian: true,
  },
  {
    id: "m-31",
    cafeId: "cafe-5",
    name: "Cappuccino",
    description: "Espresso with foamed milk",
    price: 8.5,
    image: images.menu["m-31"],
    category: "Coffee",
    popular: true,
  },
  {
    id: "m-32",
    cafeId: "cafe-5",
    name: "Chicken Mayo Sandwich",
    description: "Toasted bread with chicken & mayo filling",
    price: 7.5,
    image: images.menu["m-32"],
    category: "Light Meals",
  },
  {
    id: "m-33",
    cafeId: "cafe-5",
    name: "Chocolate Cake Slice",
    description: "Rich layered chocolate cake",
    price: 8.0,
    image: images.menu["m-33"],
    category: "Pastries",
    vegetarian: true,
  },
  // Pakya Sinar
  {
    id: "m-14",
    cafeId: "cafe-6",
    name: "Sandwich Tuna",
    description: "Ready-to-eat tuna sandwich",
    price: 4.5,
    image: images.menu["m-14"],
    category: "Snacks",
  },
  {
    id: "m-15",
    cafeId: "cafe-6",
    name: "Mineral Water 1.5L",
    description: "Bottled drinking water",
    price: 2.5,
    image: images.menu["m-15"],
    category: "Drinks",
  },
  {
    id: "m-16",
    cafeId: "cafe-6",
    name: "Potato Chips",
    description: "Assorted flavours 150g",
    price: 5.0,
    image: images.menu["m-16"],
    category: "Snacks",
  },
  {
    id: "m-34",
    cafeId: "cafe-6",
    name: "Nasi Goreng USA",
    description: "Fried rice with chicken, egg & sunny-side up",
    price: 7.5,
    image: images.menu["m-34"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-35",
    cafeId: "cafe-6",
    name: "Ayam Popcorn",
    description: "Bite-sized crispy fried chicken pieces",
    price: 8.0,
    image: images.menu["m-35"],
    category: "Snacks",
    popular: true,
  },
  {
    id: "m-36",
    cafeId: "cafe-6",
    name: "Kopi O Panas",
    description: "Hot black coffee, no sugar",
    price: 2.0,
    image: images.menu["m-36"],
    category: "Drinks",
  },
  // Cafe Richiamo
  {
    id: "m-10",
    cafeId: "cafe-7",
    name: "Latte",
    description: "Espresso with steamed milk",
    price: 9.0,
    image: images.menu["m-10"],
    category: "Coffee",
    popular: true,
  },
  {
    id: "m-11",
    cafeId: "cafe-7",
    name: "Caramel Macchiato",
    description: "Espresso, vanilla & caramel drizzle",
    price: 11.0,
    image: images.menu["m-11"],
    category: "Coffee",
    popular: true,
  },
  {
    id: "m-37",
    cafeId: "cafe-7",
    name: "Americano",
    description: "Espresso diluted with hot water",
    price: 8.0,
    image: images.menu["m-37"],
    category: "Coffee",
  },
  {
    id: "m-38",
    cafeId: "cafe-7",
    name: "Garlic Cheese Bread",
    description: "Toasted baguette with garlic butter & cheese",
    price: 7.0,
    image: images.menu["m-38"],
    category: "Light Meals",
    vegetarian: true,
  },
  {
    id: "m-39",
    cafeId: "cafe-7",
    name: "Iced Chocolate",
    description: "Rich chocolate drink served cold",
    price: 10.0,
    image: images.menu["m-39"],
    category: "Drinks",
    popular: true,
  },
  // Cafe Pedas Manis
  {
    id: "m-17",
    cafeId: "cafe-8",
    name: "Nasi Goreng Pedas",
    description: "Spicy fried rice with sambal & fried egg",
    price: 8.0,
    image: images.menu["m-17"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-18",
    cafeId: "cafe-8",
    name: "Ayam Masak Merah",
    description: "Chicken in sweet spicy tomato gravy with rice",
    price: 9.5,
    image: images.menu["m-18"],
    category: "Rice",
    popular: true,
  },
  {
    id: "m-40",
    cafeId: "cafe-8",
    name: "Sambal Udang",
    description: "Prawns in fiery sambal with steamed rice",
    price: 12.0,
    image: images.menu["m-40"],
    category: "Seafood",
  },
  {
    id: "m-41",
    cafeId: "cafe-8",
    name: "Cendol",
    description: "Iced coconut milk with palm sugar & green jelly",
    price: 4.0,
    image: images.menu["m-41"],
    category: "Desserts",
    vegetarian: true,
  },
  {
    id: "m-42",
    cafeId: "cafe-8",
    name: "Mee Rebus",
    description: "Yellow noodles in thick sweet potato gravy",
    price: 6.5,
    image: images.menu["m-42"],
    category: "Noodles",
  },
];

export const rewards: Reward[] = [
  {
    id: "r-1",
    name: "Free Teh Tarik",
    description: "Redeem at any Lendu campus outlet",
    pointsCost: 150,
    type: "drink",
    image: images.rewards["r-1"],
    expiresIn: "30 days",
  },
  {
    id: "r-2",
    name: "Free Latte",
    description: "Valid at Cafe Richiamo only",
    pointsCost: 300,
    type: "drink",
    image: images.rewards["r-2"],
    expiresIn: "30 days",
  },
  {
    id: "r-3",
    name: "RM3 Off Next Order",
    description: "Min. spend RM10",
    pointsCost: 200,
    type: "discount",
    image: images.rewards["r-3"],
    expiresIn: "14 days",
  },
  {
    id: "r-4",
    name: "RM5 Off Next Order",
    description: "Min. spend RM20",
    pointsCost: 400,
    type: "discount",
    image: images.rewards["r-4"],
    expiresIn: "14 days",
  },
  {
    id: "r-5",
    name: "Free Nasi Lemak",
    description: "Cafe Bentara exclusive",
    pointsCost: 500,
    type: "meal",
    image: images.rewards["r-5"],
    expiresIn: "7 days",
  },
  {
    id: "r-6",
    name: "10% Off Total Bill",
    description: "One-time use, all Lendu outlets",
    pointsCost: 800,
    type: "discount",
    image: images.rewards["r-6"],
    expiresIn: "7 days",
  },
];

export const transactions: Transaction[] = [
  {
    id: "t-1",
    type: "payment",
    amount: -10.5,
    date: "2026-06-24T08:15:00",
    description: "Cafe Bentara – Nasi Lemak Ayam Goreng",
    pointsEarned: 21,
  },
  {
    id: "t-2",
    type: "topup",
    amount: 50.0,
    date: "2026-06-23T14:30:00",
    description: "Wallet top-up via FPX",
  },
  {
    id: "t-3",
    type: "payment",
    amount: -5.0,
    date: "2026-06-23T12:00:00",
    description: "Pakya Sinar – Nasi Lemak Biasa",
    pointsEarned: 10,
  },
  {
    id: "t-4",
    type: "reward",
    amount: 0,
    date: "2026-06-22T16:45:00",
    description: "Redeemed: Free Teh Tarik",
    pointsEarned: -150,
  },
  {
    id: "t-5",
    type: "payment",
    amount: -9.0,
    date: "2026-06-22T10:20:00",
    description: "Cafe Richiamo – Latte",
    pointsEarned: 18,
  },
  {
    id: "t-6",
    type: "topup",
    amount: 20.0,
    date: "2026-06-20T09:00:00",
    description: "Wallet top-up via Touch 'n Go",
  },
];

export const orders: Order[] = [
  {
    id: "ORD-2847",
    cafeId: "cafe-1",
    cafeName: "Cafe Bentara",
    items: [
      { name: "Nasi Lemak Ayam Goreng", quantity: 1, price: 8.0 },
      { name: "Teh Tarik", quantity: 1, price: 2.5 },
    ],
    total: 13.0,
    status: "on_the_way",
    pickupTime: "ASAP",
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    isPreOrder: false,
    pointsEarned: 21,
    qrCode: "KK-2847-BENTARA",
    fulfillmentType: "delivery",
    deliveryLocation: {
      id: "loc-kpp1",
      label: "KPP1 Student Area",
      detail: "Block A, Ground Floor",
      zone: "KPP1",
    },
    deliveryFee: 2.5,
    estimatedDeliveryAt: new Date(Date.now() + 11 * 60 * 1000).toISOString(),
    driverName: "Amirul H.",
    driverPhone: "+6012-345 6789",
  },
  {
    id: "ORD-2831",
    cafeId: "cafe-7",
    cafeName: "Cafe Richiamo",
    items: [{ name: "Latte", quantity: 1, price: 9.0 }],
    total: 9.0,
    status: "completed",
    pickupTime: "10:15 AM",
    createdAt: "2026-06-22T10:05:00",
    isPreOrder: false,
    pointsEarned: 18,
    qrCode: "KK-2831-RICH",
    fulfillmentType: "pickup",
  },
  {
    id: "ORD-2819",
    cafeId: "cafe-6",
    cafeName: "Pakya Sinar",
    items: [
      { name: "Sandwich Tuna", quantity: 1, price: 4.5 },
      { name: "Mineral Water 1.5L", quantity: 1, price: 2.5 },
    ],
    total: 7.0,
    status: "completed",
    pickupTime: "1:00 PM",
    createdAt: "2026-06-21T12:30:00",
    isPreOrder: true,
    pointsEarned: 14,
    qrCode: "KK-2819-PAKYA",
    fulfillmentType: "pickup",
  },
];

export const preOrderSlots: PreOrderSlot[] = [
  { id: "h-8", time: "8:00 AM", available: true },
  { id: "h-9", time: "9:00 AM", available: true },
  { id: "h-10", time: "10:00 AM", available: true },
  { id: "h-11", time: "11:00 AM", available: true },
  { id: "h-12", time: "12:00 PM", available: true },
  { id: "h-13", time: "1:00 PM", available: true },
  { id: "h-14", time: "2:00 PM", available: true },
  { id: "h-15", time: "3:00 PM", available: true },
  { id: "h-16", time: "4:00 PM", available: true },
  { id: "h-17", time: "5:00 PM", available: true },
  { id: "h-18", time: "6:00 PM", available: true },
  { id: "h-19", time: "7:00 PM", available: true },
  { id: "h-20", time: "8:00 PM", available: true },
  { id: "h-21", time: "9:00 PM", available: true },
  { id: "h-22", time: "10:00 PM", available: true },
  { id: "h-23", time: "11:00 PM", available: true },
];

export const topUpOptions: TopUpOption[] = [
  { amount: 10 },
  { amount: 20, popular: true },
  { amount: 50, bonus: 2 },
  { amount: 100, bonus: 5, popular: true },
];

export const paymentMethods = [
  { id: "wallet", name: "LenduEats Wallet", icon: "wallet" as const },
  { id: "fpx", name: "Online Banking (FPX)", icon: "bank" as const },
  { id: "tng", name: "Touch 'n Go eWallet", icon: "smartphone" as const },
];

export const promoBanners = [
  {
    id: "p-1",
    title: "Double Points Week!",
    subtitle: "Earn 2× LenduEats Points on all orders",
    href: "/rewards",
    image: images.promos["p-1"],
    color: "from-uitm-navy/90 to-uitm-magenta/90",
  },
  {
    id: "p-2",
    title: "Campus Delivery",
    subtitle: "Order to your kolej or KPP — track live ETA",
    href: "/cafes",
    image: images.promos["p-2"],
    color: "from-uitm-magenta/90 to-uitm-navy/90",
  },
];

export const tierBenefits = {
  Bronze: { multiplier: 1, nextTier: "Silver", pointsNeeded: 500 },
  Silver: { multiplier: 1.5, nextTier: "Gold", pointsNeeded: 2000 },
  Gold: { multiplier: 2, nextTier: null, pointsNeeded: 0 },
};

export const tierDetails = [
  {
    tier: "Bronze" as const,
    minPoints: 0,
    multiplier: 1,
    perks: ["2 points per RM1 spent", "Access to basic rewards"],
  },
  {
    tier: "Silver" as const,
    minPoints: 500,
    multiplier: 1.5,
    perks: ["1.5× points on every order", "Birthday free drink", "Promo early access"],
  },
  {
    tier: "Gold" as const,
    minPoints: 2000,
    multiplier: 2,
    perks: ["2× points on every order", "Priority pickup queue", "Exclusive Gold rewards"],
  },
];

export function formatCurrency(amount: number): string {
  return `RM ${Math.abs(amount).toFixed(2)}`;
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-MY", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function formatTime(dateStr: string): string {
  return new Date(dateStr).toLocaleTimeString("en-MY", {
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function getCafeById(id: string): Cafe | undefined {
  return cafes.find((c) => c.id === id);
}

export function getMenuByCafe(cafeId: string): MenuItem[] {
  return menuItems.filter((m) => m.cafeId === cafeId);
}
